set termout off
set pagesize 0
set feedback off
set heading off
SET TRIMSPOOL ON
set linesize 2000
spool D:\BI_Report\work\contract_tracking_report.&1..txt
set verify off
SELECT 
'CONTRACTID'||','||
'EDITBUID'||','||
'REFSHEETID'||','||
'REFSHEETTYPE'||','||
'BUID'||','||
'VENDERID'||','||
'VENDERCODE'||','||
'SYSVENDERID'||','||
'VENDERSTATUS'||','||
'CHECKER'||','||
'CHECKDATE'||','||
'CONTRACTTYPE'||','||
'CONSHEETTYPE'||','||
'MASTERCONTRACTID'||','||
'BUCONTRACTID'||','||
'SUBFLAG'||','||
'REFCONTRACTID'||','||
'REFCONTRACTVER'||','||
'HEADCONTYPE'||','||
'HEADVENDERID'||','||
'HEADVENDERCODE'||','||
'HEADSYSVENDERID'||','||
'CONTRACTCODE'||','||
'CONTRACTVER'||','||
'FIRSTPARTY'||','||
'SECONDPARTY'||','||
'FIRSTPARTYREPR'||','||
'SECONDPARTYREPR'||','||
'FIRSTPARTYAGENT'||','||
'SECONDPARTYAGENT'||','||
'CONTYPE'||','||
'BUCONFIRMNUM'||','||
'CSTARTDATE'||','||
'CENDDATE'||','||
'ASTARTDATE'||','||
'AENDDATE'||','||
'CONTRACTSTATUS'||','||
'CONTRACTSHOPID'||','||
'CONTRACTOFFICEID'||','||
'CONTRACTBULL'||','||
'PURDAY'||','||
'BUDGET'||','||
'SPONSIONCOMPANY'||','||
'SALEPAYFLAG'||','||
'DEALTAXFLAG'||','||
'DEALTAXRATE'||','||
'HANDLINGFEERATE'||','||
'CONTRACTLIMIT'||','||
'RETAILFORMID'||','||
'BUIDLIST'||','||
'RETFLAG'||','||
'PAYTYPEID'||','||
'CONTEXTFLAG'||','||
'NOTE'||','||
'DEDUCTRATE'||','||
'TRACEFLAG'||','||
'CONFIRMER'||','||
'CONFIRMDATE'||','||
'RCONFIRMER'||','||
'RCONFIRMDATE'||','||
'HEADVENDERNAME'||','||
'VENDERFLAG' FROM dual
UNION 
SELECT DISTINCT A.CONTRACTID||','||
A.EDITBUID||','||
A.REFSHEETID||','||
A.REFSHEETTYPE||','||
A.BUID||','||
A.VENDERID||','||
A.VENDERCODE||','||
A.SYSVENDERID||','||
B.VENDERSTATUS||','||
D.CHECKER||','||
C.CHECKDATE||','||
A.CONTRACTTYPE||','||
A.CONSHEETTYPE||','||
A.MASTERCONTRACTID||','||
A.BUCONTRACTID||','||
A.SUBFLAG||','||
A.REFCONTRACTID||','||
A.REFCONTRACTVER||','||
A.HEADCONTYPE||','||
A.HEADVENDERID||','||
A.HEADVENDERCODE||','||
A.HEADSYSVENDERID||','||
A.CONTRACTCODE||','||
A.CONTRACTVER||','||
A.FIRSTPARTY||','||
A.SECONDPARTY||','||
A.FIRSTPARTYREPR||','||
A.SECONDPARTYREPR||','||
A.FIRSTPARTYAGENT||','||
A.SECONDPARTYAGENT||','||
A.CONTYPE||','||
A.BUCONFIRMNUM||','||
A.CSTARTDATE||','||
A.CENDDATE||','||
A.ASTARTDATE||','||
A.AENDDATE||','||
A.CONTRACTSTATUS||','||
A.CONTRACTSHOPID||','||
A.CONTRACTOFFICEID||','||
A.CONTRACTBULL||','||
A.PURDAY||','||
A.BUDGET||','||
A.SPONSIONCOMPANY||','||
A.SALEPAYFLAG||','||
A.DEALTAXFLAG||','||
A.DEALTAXRATE||','||
A.HANDLINGFEERATE||','||
A.CONTRACTLIMIT||','||
A.RETAILFORMID||','||
A.BUIDLIST||','||
A.RETFLAG||','||
A.PAYTYPEID||','||
A.CONTEXTFLAG||','||
A.NOTE||','||
A.DEDUCTRATE||','||
A.TRACEFLAG||','||
A.CONFIRMER||','||
A.CONFIRMDATE||','||
A.RCONFIRMER||','||
A.RCONFIRMDATE||','||
A.HEADVENDERNAME||','||
A.VENDERFLAG
FROM DBUSRSUPPERHQ.SCONTRACT A,
DBUSRMASTER.VENDER B,
(SELECT SC.SHEETID, SC.CONTRACTID, SCO.CHECKDATE
FROM DBUSRSUPPERHQ.SCONSHEET  SC,
(SELECT CONTRACTID, MAX(CHECKDATE) CHECKDATE
FROM DBUSRSUPPERHQ.SCONSHEET 
WHERE FLAG = 100 
GROUP BY CONTRACTID) SCO
WHERE SC.CONTRACTID = SCO.CONTRACTID
AND SC.CHECKDATE = SCO.CHECKDATE) C,
DBUSRSUPPERHQ.SCONSHEET D
WHERE A.VENDERID = B.VENDERID
AND A.CONTRACTID = D.CONTRACTID
AND A.BUID = B.BUID
AND A.BUID = 31
AND C.SHEETID = D.SHEETID
UNION ALL
SELECT DISTINCT A.CONTRACTID||','||
A.EDITBUID||','||
A.REFSHEETID||','||
A.REFSHEETTYPE||','||
A.BUID||','||
A.VENDERID||','||
A.VENDERCODE||','||
A.SYSVENDERID||','||
B.VENDERSTATUS||','||
D.CHECKER||','||
C.CHECKDATE||','||
A.CONTRACTTYPE||','||
A.CONSHEETTYPE||','||
A.MASTERCONTRACTID||','||
A.BUCONTRACTID||','||
A.SUBFLAG||','||
A.REFCONTRACTID||','||
A.REFCONTRACTVER||','||
A.HEADCONTYPE||','||
A.HEADVENDERID||','||
A.HEADVENDERCODE||','||
A.HEADSYSVENDERID||','||
A.CONTRACTCODE||','||
A.CONTRACTVER||','||
A.FIRSTPARTY||','||
A.SECONDPARTY||','||
A.FIRSTPARTYREPR||','||
A.SECONDPARTYREPR||','||
A.FIRSTPARTYAGENT||','||
A.SECONDPARTYAGENT||','||
A.CONTYPE||','||
A.BUCONFIRMNUM||','||
A.CSTARTDATE||','||
A.CENDDATE||','||
A.ASTARTDATE||','||
A.AENDDATE||','||
A.CONTRACTSTATUS||','||
A.CONTRACTSHOPID||','||
A.CONTRACTOFFICEID||','||
A.CONTRACTBULL||','||
A.PURDAY||','||
A.BUDGET||','||
A.SPONSIONCOMPANY||','||
A.SALEPAYFLAG||','||
A.DEALTAXFLAG||','||
A.DEALTAXRATE||','||
A.HANDLINGFEERATE||','||
A.CONTRACTLIMIT||','||
A.RETAILFORMID||','||
A.BUIDLIST||','||
A.RETFLAG||','||
A.PAYTYPEID||','||
A.CONTEXTFLAG||','||
A.NOTE||','||
A.DEDUCTRATE||','||
A.TRACEFLAG||','||
A.CONFIRMER||','||
A.CONFIRMDATE||','||
A.RCONFIRMER||','||
A.RCONFIRMDATE||','||
A.HEADVENDERNAME||','||
A.VENDERFLAG
FROM DBUSRSUPPERHQ.SCONTRACT A,
DBUSRMASTER.VENDER B,
(SELECT SC.SHEETID, SC.CONTRACTID, SCO.CHECKDATE
FROM DBUSRSUPPERHQ.UCONSHEET  SC,
(SELECT CONTRACTID, MAX(CHECKDATE) CHECKDATE
FROM DBUSRSUPPERHQ.UCONSHEET 
WHERE FLAG = 100 
GROUP BY CONTRACTID) SCO
WHERE SC.CONTRACTID = SCO.CONTRACTID
AND SC.CHECKDATE = SCO.CHECKDATE) C,
DBUSRSUPPERHQ.UCONSHEET D
WHERE A.VENDERID = B.VENDERID
AND A.CONTRACTID = D.CONTRACTID
AND A.BUID = B.BUID
AND A.BUID = 31
AND C.SHEETID = D.SHEETID
UNION ALL
SELECT DISTINCT A.CONTRACTID||','||
A.EDITBUID||','||
A.REFSHEETID||','||
A.REFSHEETTYPE||','||
A.BUID||','||
A.VENDERID||','||
A.VENDERCODE||','||
A.SYSVENDERID||','||
B.VENDERSTATUS||','||
D.CHECKER||','||
C.CHECKDATE||','||
A.CONTRACTTYPE||','||
A.CONSHEETTYPE||','||
A.MASTERCONTRACTID||','||
A.BUCONTRACTID||','||
A.SUBFLAG||','||
A.REFCONTRACTID||','||
A.REFCONTRACTVER||','||
A.HEADCONTYPE||','||
A.HEADVENDERID||','||
A.HEADVENDERCODE||','||
A.HEADSYSVENDERID||','||
A.CONTRACTCODE||','||
A.CONTRACTVER||','||
A.FIRSTPARTY||','||
A.SECONDPARTY||','||
A.FIRSTPARTYREPR||','||
A.SECONDPARTYREPR||','||
A.FIRSTPARTYAGENT||','||
A.SECONDPARTYAGENT||','||
A.CONTYPE||','||
A.BUCONFIRMNUM||','||
A.CSTARTDATE||','||
A.CENDDATE||','||
A.ASTARTDATE||','||
A.AENDDATE||','||
A.CONTRACTSTATUS||','||
A.CONTRACTSHOPID||','||
A.CONTRACTOFFICEID||','||
A.CONTRACTBULL||','||
A.PURDAY||','||
A.BUDGET||','||
A.SPONSIONCOMPANY||','||
A.SALEPAYFLAG||','||
A.DEALTAXFLAG||','||
A.DEALTAXRATE||','||
A.HANDLINGFEERATE||','||
A.CONTRACTLIMIT||','||
A.RETAILFORMID||','||
A.BUIDLIST||','||
A.RETFLAG||','||
A.PAYTYPEID||','||
A.CONTEXTFLAG||','||
A.NOTE||','||
A.DEDUCTRATE||','||
A.TRACEFLAG||','||
A.CONFIRMER||','||
A.CONFIRMDATE||','||
A.RCONFIRMER||','||
A.RCONFIRMDATE||','||
A.HEADVENDERNAME||','||
A.VENDERFLAG
FROM DBUSRSUPPERHQ.SCONTRACT A,
DBUSRMASTER.VENDER B,
(SELECT SC.SHEETID, SC.CONTRACTID, SCO.CHECKDATE
FROM DBUSRSUPPERHQ.RCONSHEET  SC,
(SELECT CONTRACTID, MAX(CHECKDATE) CHECKDATE
FROM DBUSRSUPPERHQ.RCONSHEET 
WHERE FLAG = 100 
GROUP BY CONTRACTID) SCO
WHERE SC.CONTRACTID = SCO.CONTRACTID
AND SC.CHECKDATE = SCO.CHECKDATE) C,
DBUSRSUPPERHQ.RCONSHEET D
WHERE A.VENDERID = B.VENDERID
AND A.CONTRACTID = D.CONTRACTID
AND A.BUID = B.BUID
AND A.BUID = 31
AND C.SHEETID = D.SHEETID
ORDER BY 1 DESC;
spool off;
exit;

